version: '3.8'

services:
  h2:
    image: oscarfonts/h2
    ports:
      - "1521:1521"
      - "8083:81"
    volumes:
      - ./data:/opt/h2-data
    environment:
      H2_OPTIONS: -tcp -tcpAllowOthers -web -webAllowOthers -baseDir /opt/h2-data -ifNotExists
  app1:
    build: .
    container_name: spring-app-1
    ports:
      - "8081:8080"

  app2:
    build: .
    container_name: spring-app-2
    ports:
      - "8082:8080"

  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
